version: "2.4"

services:
  backend:
    container_name: giftcard-backend
    build:
      context: ./backend
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "5091:5091"
    restart: unless-stopped
    environment:
      - TZ=America/Vancouver

  frontend:
    container_name: giftcard-frontend
    build:
      context: ./frontend
    ports:
      - "5092:5092"
    depends_on:
      - backend
    restart: unless-stopped

